import {StyleSheet} from 'react-native';
import colors from '../../utils/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.darkblue,
  },
  headview: {
    flex: 0.15,
    flexDirection: 'row',
    paddingHorizontal: 15,
  },
  detview: {
    flex: 0.85,
    backgroundColor: colors.white,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
  },
  menu: {
    height: 50,
    width: 50,
    backgroundColor: colors.red,
    borderRadius: 100,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  menuimg: {
    height: '60%',
    resizeMode: 'contain',
    tintColor: colors.white,
  },
  pointimg: {
    height: 20,
    resizeMode: 'contain',
    alignSelf: 'flex-start',
    top: 3,
    tintColor: colors.white,
  },
  headtxtview: {
    flex: 0.8,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  headtxt: {
    fontSize: 30,
    fontWeight: 'bold',
    color: colors.yellow,
    fontFamily: 'sans-serif-condensed',
  },
  sec1: {
    height: 320,
    marginVertical: 20,
    marginHorizontal: 20,
    backgroundColor: colors.yellow,
    borderColor: 'orange',
    borderWidth: 5,
    borderRadius: 30,
    overflow: 'hidden',
  },
  sec2: {
    height: 300,
    marginVertical: 20,
    marginHorizontal: 20,
    backgroundColor: colors.red,
    borderColor: 'red',
    borderWidth: 5,
    borderRadius: 30,
    overflow: 'hidden',
  },
  sec3: {
    height: 300,
    marginVertical: 20,
    marginHorizontal: 20,
    backgroundColor: colors.grey,
    borderColor: colors.greyish,
    borderWidth: 5,
    borderRadius: 30,
    overflow: 'hidden',
  },
  subsec1: {
    flex: 0.2,
    backgroundColor: 'orange',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subsec2: {
    flex: 0.2,
    backgroundColor: 'red',
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subsec3: {
    flex: 0.2,
    backgroundColor: colors.greyish,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  part: {
    width: '80%',
    alignItems: 'center',
    flexDirection: 'row',
  },
  hismlltext: {
    color: colors.white,
    fontSize: 30,
    fontWeight: '800',
    fontFamily: 'sans-serif-condensed',
  },
  smlltext: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'sans-serif-condensed',
  },
});
